/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entities.*;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Juha
 */
public class Menu extends javax.swing.JFrame {

    private DefaultTableModel mod;
    private DefaultTableModel dtm;
    private DefaultTableModel model;
    private TableRowSorter<DefaultTableModel> sorter;
    private DefaultTableCellRenderer centerRenderer;
    private int authorCounter = 0;
    private int categoryCounter = 0;
    private int editBookAuthorCounter = 0;
    private int editBookCategoryCounter = 0;
    private int id = 0;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelBrowse = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Object col[] = {"ID", "Kirjailija", "Nimi", "Julkaisuvuosi", "Kategoria", "Lainassa", "Lainaaja", "Alkuperäinen nimi"};
        mod = new DefaultTableModel(null, col) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            @Override
            public Class getColumnClass(int column){
                switch (column) {
                    case 0:
                    return Integer.class;
                    case 3:
                    return Integer.class;
                    case 5:
                    return Boolean.class;
                    default:
                    return String.class;
                }
            }
        };
        browseTable = new javax.swing.JTable()
        ;
        filterAuthor = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        panelAdd = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtAddAuthorFirstName = new javax.swing.JTextField();
        txtAddAuthorLastName = new javax.swing.JTextField();
        lblAddAuthor = new javax.swing.JLabel();
        btnAddAuthor = new javax.swing.JButton();
        lblAddCategoryHeader = new javax.swing.JLabel();
        lblAddCategory = new javax.swing.JLabel();
        txtAddCategory = new javax.swing.JTextField();
        btnAddCategory = new javax.swing.JButton();
        lblAddBook = new javax.swing.JLabel();
        ArrayList<Author> authors = Author.getAuthors();
        cBoxAuthor = new javax.swing.JComboBox();
        ArrayList<Category> categories = Category.getCategories();
        cBoxCategory = new javax.swing.JComboBox();
        lblBookName = new javax.swing.JLabel();
        lblOrigName = new javax.swing.JLabel();
        lblPubYear = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        txtPubYear = new javax.swing.JTextField();
        txtOriginalName = new javax.swing.JTextField();
        txtLoaner = new javax.swing.JTextField();
        btnAddBook = new javax.swing.JButton();
        checkLoan = new javax.swing.JCheckBox();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        lblStar = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Object cols[] = {"Kirjailija", "Kategoria"};
        dtm = new DefaultTableModel(null, cols) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        addManyTable = new javax.swing.JTable();
        btnAuthorToTable = new javax.swing.JButton();
        btnCatToTable = new javax.swing.JButton();
        star5 = new javax.swing.JLabel();
        panelEdit = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Object columns[] = {"Kirjailija", "Kategoria"};
        model = new DefaultTableModel(null, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return true;
            }
        };
        editBookTable = new javax.swing.JTable()
        ;
        lblEditBookHeader = new javax.swing.JLabel();
        btnSaveChanges = new javax.swing.JButton();
        lblEditBookName = new javax.swing.JLabel();
        lblEditBookPubYear = new javax.swing.JLabel();
        lblEditBookOrigName = new javax.swing.JLabel();
        checkEditLoan = new javax.swing.JCheckBox();
        txtEditBookName = new javax.swing.JTextField();
        txtEditPubYear = new javax.swing.JTextField();
        txtEditOrigName = new javax.swing.JTextField();
        txtEditLoaner = new javax.swing.JTextField();
        ArrayList<Author> authors1 = Author.getAuthors();
        cBoxEditBookAuthor = new javax.swing.JComboBox();
        ArrayList<Category> categories1 = Category.getCategories();
        cBoxEditBookCategory = new javax.swing.JComboBox();
        btnClearEditBoxes = new javax.swing.JButton();
        btnEditBookAddAuthor = new javax.swing.JButton();
        btnEditBookAddCategory = new javax.swing.JButton();
        btnEditBookDeleteAuthor = new javax.swing.JButton();
        btnEditBookDeleteCategory = new javax.swing.JButton();
        lblEditAuthorHeader = new javax.swing.JLabel();
        lblEditAuthorFirstName = new javax.swing.JLabel();
        ArrayList<Author> authors2 = Author.getAuthors();
        cBoxEditAuthor = new javax.swing.JComboBox();
        txtEditAuthorLastName = new javax.swing.JTextField();
        txtEditAuthorName = new javax.swing.JTextField();
        btnEditAuthor = new javax.swing.JButton();
        lblEditAuthorLastName = new javax.swing.JLabel();
        lblEditCategoryHeader = new javax.swing.JLabel();
        ArrayList<Category> categories2 = Category.getCategories();
        cBoxEditCategory = new javax.swing.JComboBox();
        txtEditCategory = new javax.swing.JTextField();
        lblEditCategoryName = new javax.swing.JLabel();
        btnEditCategory = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        ((JComponent) browseTable.getDefaultRenderer(Boolean.class)).setOpaque(true);
        sorter = new TableRowSorter<DefaultTableModel>(mod);
        browseTable.setAutoCreateRowSorter(true);
        browseTable.setModel(mod);
        fillTable();
        browseTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if(browseTable.getSelectedRow() != -1) {
                    id = (Integer) browseTable.getValueAt(browseTable.getSelectedRow(), 0);
                    fillEditBookTable();
                }
            }
        });
        jScrollPane1.setViewportView(browseTable);

        filterAuthor.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                newFilter();
            }
            public void insertUpdate(DocumentEvent e) {
                newFilter();
            }
            public void removeUpdate(DocumentEvent e) {
                newFilter();
            }
        });
        filterAuthor.setToolTipText("Kirjoita osa kirjailijan tai kirjan nimestä, tai vuodesta");

        lblSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSearch.setText("Haku");

        javax.swing.GroupLayout panelBrowseLayout = new javax.swing.GroupLayout(panelBrowse);
        panelBrowse.setLayout(panelBrowseLayout);
        panelBrowseLayout.setHorizontalGroup(
            panelBrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBrowseLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelBrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
                    .addGroup(panelBrowseLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblSearch)
                        .addGap(18, 18, 18)
                        .addComponent(filterAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        panelBrowseLayout.setVerticalGroup(
            panelBrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBrowseLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(panelBrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Selaa", panelBrowse);

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFirstName.setText("Etunimi");

        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLastName.setText("Sukunimi");

        lblAddAuthor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAddAuthor.setText("Kirjailijan lisääminen");

        btnAddAuthor.setText("Lisää kirjailija");
        btnAddAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAuthorActionPerformed(evt);
            }
        });

        lblAddCategoryHeader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAddCategoryHeader.setText("Kategorian lisääminen");

        lblAddCategory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddCategory.setText("Kategoria");

        btnAddCategory.setText("Lisää kategoria");
        btnAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoryActionPerformed(evt);
            }
        });

        lblAddBook.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAddBook.setText("Kirjan lisääminen");

        cBoxAuthor.setModel(new javax.swing.DefaultComboBoxModel());

        cBoxCategory.setModel(new javax.swing.DefaultComboBoxModel());

        lblBookName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBookName.setText("Kirjan nimi");

        lblOrigName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOrigName.setText("Alkuperäinen nimi");

        lblPubYear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPubYear.setText("Julkaisuvuosi");
        lblPubYear.setToolTipText("Nelinumeroinen vuosiluku, esim. 1994");

        btnAddBook.setText("Lisää kirja");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        checkLoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkLoan.setText("Lainassa / Lainaaja");
        checkLoan.setToolTipText("Laita rasti ruutuun jos kirja on lainassa");

        star1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        star1.setForeground(new java.awt.Color(255, 0, 0));
        star1.setText("*");
        star1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        star2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        star2.setForeground(new java.awt.Color(255, 0, 0));
        star2.setText("*");
        star2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        star4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        star4.setForeground(new java.awt.Color(255, 0, 0));
        star4.setText("*");
        star4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblStar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStar.setText("Tähdellä merkityt ovat pakollisia tietoja");

        star3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        star3.setForeground(new java.awt.Color(255, 0, 0));
        star3.setText("*");
        star3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnClear.setText("Tyhjennä");
        btnClear.setToolTipText("Paina tyhjentääksesi 'Lisää kirja'-lomakkeen tekstikentät");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        addManyTable.setModel(dtm);
        fillAddManyTable();
        jScrollPane2.setViewportView(addManyTable);

        btnAuthorToTable.setText("Lisää kirjailija");
        btnAuthorToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorToTableActionPerformed(evt);
            }
        });

        btnCatToTable.setText("Lisää kategoria");
        btnCatToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatToTableActionPerformed(evt);
            }
        });

        star5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        star5.setForeground(new java.awt.Color(255, 0, 0));
        star5.setText("*");
        star5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        for(Author a : authors){
            cBoxAuthor.addItem(a.getLastName() + ", " + a.getName());
        }
        cBoxAuthor.setSelectedIndex(-1);
        for(Category c : categories){
            cBoxCategory.addItem(c.getName());
        }
        cBoxCategory.setSelectedIndex(-1);

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddBook)
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddLayout.createSequentialGroup()
                                .addComponent(btnAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddLayout.createSequentialGroup()
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPubYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPubYear, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(txtBookName)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                                        .addComponent(lblAddCategory)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddLayout.createSequentialGroup()
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkLoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOrigName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLoaner)
                                    .addComponent(txtOriginalName)))
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cBoxAuthor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAuthorToTable, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addComponent(star4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCatToTable, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addComponent(star5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStar, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAddAuthor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddLayout.createSequentialGroup()
                                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFirstName)
                                        .addComponent(lblLastName))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtAddAuthorLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addComponent(txtAddAuthorFirstName))))
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addComponent(lblAddAuthor)
                                .addGap(56, 56, 56)
                                .addComponent(lblAddCategoryHeader)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(star2)
                            .addComponent(star3)
                            .addComponent(star1))))
                .addContainerGap(776, Short.MAX_VALUE))
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddAuthor)
                    .addComponent(lblAddCategoryHeader))
                .addGap(14, 14, 14)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtAddAuthorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddCategory)
                    .addComponent(txtAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtAddAuthorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAuthor)
                    .addComponent(btnAddCategory))
                .addGap(28, 28, 28)
                .addComponent(lblAddBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(star2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBookName)
                        .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPubYear)
                    .addComponent(txtPubYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(star1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigName)
                    .addComponent(txtOriginalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkLoan)
                    .addComponent(txtLoaner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(star4)
                    .addComponent(star3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAuthorToTable)
                    .addComponent(btnCatToTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBook)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStar)
                    .addComponent(star5))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lisää...", panelAdd);

        editBookTable.setModel(model);
        fillEditBookTable();
        jScrollPane3.setViewportView(editBookTable);

        lblEditBookHeader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEditBookHeader.setText("Kirjan muokkaus");

        btnSaveChanges.setText("Tallenna muutokset");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        lblEditBookName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEditBookName.setText("Kirjan nimi");

        lblEditBookPubYear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEditBookPubYear.setText("Julkaisuvuosi");

        lblEditBookOrigName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEditBookOrigName.setText("Alkuperäinen nimi");

        checkEditLoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkEditLoan.setText("Lainassa / Lainaaja");

        cBoxEditBookAuthor.setModel(new javax.swing.DefaultComboBoxModel());

        cBoxEditBookCategory.setModel(new javax.swing.DefaultComboBoxModel());
        for(Category c : categories1){
            cBoxEditBookCategory.addItem(c.getName());
        }
        cBoxEditBookCategory.setSelectedIndex(-1);

        btnClearEditBoxes.setText("Tyhjennä");
        btnClearEditBoxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearEditBoxesActionPerformed(evt);
            }
        });

        btnEditBookAddAuthor.setText("Lisää kirjailija");
        btnEditBookAddAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBookAddAuthorActionPerformed(evt);
            }
        });

        btnEditBookAddCategory.setText("Lisää kategoria");
        btnEditBookAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBookAddCategoryActionPerformed(evt);
            }
        });

        btnEditBookDeleteAuthor.setText("Poista kirjailija");
        btnEditBookDeleteAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBookDeleteAuthorActionPerformed(evt);
            }
        });

        btnEditBookDeleteCategory.setText("Poista kategoria");
        btnEditBookDeleteCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBookDeleteCategoryActionPerformed(evt);
            }
        });

        lblEditAuthorHeader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEditAuthorHeader.setText("Kirjailijan muokkaus");

        lblEditAuthorFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEditAuthorFirstName.setText("Etunimi");

        cBoxEditAuthor.setModel(new javax.swing.DefaultComboBoxModel());
        for(Author a : authors2){
            cBoxEditAuthor.addItem(a.getLastName() + ", " + a.getName());
        }
        cBoxEditAuthor.setSelectedIndex(-1);
        cBoxEditAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxEditAuthorActionPerformed(evt);
            }
        });

        btnEditAuthor.setText("Muokkaa kirjailija");
        btnEditAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAuthorActionPerformed(evt);
            }
        });

        lblEditAuthorLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEditAuthorLastName.setText("Sukunimi");

        lblEditCategoryHeader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEditCategoryHeader.setText("Kategorian muokkaus");

        cBoxEditCategory.setModel(new javax.swing.DefaultComboBoxModel());
        for(Category c : categories2){
            cBoxEditCategory.addItem(c.getName());
        }
        cBoxEditCategory.setSelectedIndex(-1);
        cBoxEditCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxEditCategoryActionPerformed(evt);
            }
        });

        lblEditCategoryName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEditCategoryName.setText("Nimi");

        btnEditCategory.setText("Muokkaa kategoria");
        btnEditCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCategoryActionPerformed(evt);
            }
        });

        for(Author a : authors1){
            cBoxEditBookAuthor.addItem(a.getLastName() + ", " + a.getName());
        }
        cBoxEditBookAuthor.setSelectedIndex(-1);

        javax.swing.GroupLayout panelEditLayout = new javax.swing.GroupLayout(panelEdit);
        panelEdit.setLayout(panelEditLayout);
        panelEditLayout.setHorizontalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEditBookHeader)
                    .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditLayout.createSequentialGroup()
                            .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClearEditBoxes, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditLayout.createSequentialGroup()
                            .addComponent(cBoxEditBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cBoxEditBookCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelEditLayout.createSequentialGroup()
                            .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEditAuthorFirstName)
                                .addComponent(lblEditAuthorLastName))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEditAuthorLastName)
                                .addComponent(txtEditAuthorName))
                            .addGap(231, 231, 231))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditLayout.createSequentialGroup()
                            .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnEditBookAddAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEditBookDeleteAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(59, 59, 59)
                            .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnEditBookAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEditBookDeleteCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditLayout.createSequentialGroup()
                        .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEditLayout.createSequentialGroup()
                                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEditAuthorHeader)
                                    .addComponent(cBoxEditAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditLayout.createSequentialGroup()
                                .addComponent(btnEditAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)))
                        .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cBoxEditCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEditCategoryHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditLayout.createSequentialGroup()
                                .addComponent(lblEditCategoryName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEditCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEditCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditLayout.createSequentialGroup()
                        .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkEditLoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEditBookPubYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEditBookOrigName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEditBookName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEditOrigName, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(txtEditPubYear)
                                .addComponent(txtEditBookName))
                            .addComponent(txtEditLoaner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(789, Short.MAX_VALUE))
        );
        panelEditLayout.setVerticalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditAuthorHeader)
                    .addComponent(lblEditCategoryHeader))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxEditAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxEditCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditAuthorFirstName)
                    .addComponent(txtEditAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditCategoryName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditAuthorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditAuthorLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditAuthor)
                    .addComponent(btnEditCategory))
                .addGap(18, 18, 18)
                .addComponent(lblEditBookHeader)
                .addGap(18, 18, 18)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditBookName)
                    .addComponent(txtEditBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditBookPubYear)
                    .addComponent(txtEditPubYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditBookOrigName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditOrigName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkEditLoan)
                    .addComponent(txtEditLoaner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxEditBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxEditBookCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditBookAddAuthor)
                    .addComponent(btnEditBookAddCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditBookDeleteAuthor)
                    .addComponent(btnEditBookDeleteCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveChanges)
                    .addComponent(btnClearEditBoxes))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Muokkaa...", panelEdit);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jMenu1.setText("Tiedosto");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Muokkaa");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ohje");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        fillTable();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnEditBookAddAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBookAddAuthorActionPerformed
        try {
            String author = cBoxEditBookAuthor.getSelectedItem().toString();
            if(editBookTable.getRowCount() > 1) {
                for (int i = 0; i < 6; i++) {
                    if (editBookTable.getValueAt(i, 0).toString().equalsIgnoreCase(author)) {
                        JOptionPane.showMessageDialog(null, "Kirjailija löytyy jo taulukosta", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
                        i = 6;
                    } else if (editBookTable.getValueAt(i, 0).toString().length() < 1) {
                        editBookTable.setValueAt(author, i, 0);
                        editBookAuthorCounter++;
                        i = 6;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Valitse ensin selausvalikosta muokattava kirja", "Virhe", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valitse pudotusvalikosta lisättävä kirjailija", "Virhe", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditBookAddAuthorActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        Book b = new Book();
        b.getBook(id);
        
        String newName = txtEditBookName.getText();
        String newPubYear = txtEditPubYear.getText();
        boolean newOnLoan = checkEditLoan.isSelected();
        String newLoaner = txtEditLoaner.getText();
        String newOrigName = txtEditOrigName.getText();
        
        ArrayList<Author> authors = new ArrayList();
        ArrayList<Category> categories = new ArrayList();
        
        b.setName(newName);
        b.setLoaner(newLoaner);
        b.setOnLoan(newOnLoan);
        b.setOrigName(newOrigName);
        
        for (int i = 0; i < editBookAuthorCounter; i++) {
            Author a = new Author();
            String auth = editBookTable.getValueAt(i, 0).toString();
            String[] authName = auth.split(", ");
            String lName = authName[0];
            String fName = authName[1];
            a.getAuthor(fName, lName);
            a.getBooks();
            authors.add(a);
        }

        for (int i = 0; i < editBookCategoryCounter; i++) {
            Category c = new Category();
            String cat = editBookTable.getValueAt(i, 1).toString();
            c.getCategory(cat);
            categories.add(c);
        }

        if (checkPubYear()) {
            if (!newName.isEmpty()) {
                boolean bookExists = false;
                for (Author a : authors) {
                    for (Book bo : a.books) {
                        if (newName.equalsIgnoreCase(bo.getName()) && Integer.parseInt(newPubYear) == bo.getPubYear()) {
                            bookExists = true;
                        }
                    }
                }
                if (!bookExists) {
                    Book b = new Book(name, origName, Integer.parseInt(pubYear), onLoan, loaner);
                    for (Category c : categories) {
                        b.category.add(c);
                    }
                    for (Author a : authors) {
                        b.author.add(a);
                    }
                    b.addBook();
                    checkEditLoan.setSelected(false);
                    clearEditBoxes();
                } else {
                    JOptionPane.showMessageDialog(null, "Kirja löytyy jo tietokannasta", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void btnCatToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatToTableActionPerformed
        String category = cBoxCategory.getSelectedItem().toString();
        Boolean addToTable = true;
        if(categoryCounter < 6) {
            for (int i = 0; i <= categoryCounter; i++) {
                if (addManyTable.getValueAt(i, 1).toString().equalsIgnoreCase(category)) {
                    addToTable = false;
                }
            }
            if (addToTable) {
                addManyTable.setValueAt(category, categoryCounter, 1);
                categoryCounter++;
            } else {
                JOptionPane.showMessageDialog(null, "Kategoria löytyy jo taulukosta", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kirjalla voi olla korkeintaan kuusi kategoriaa", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCatToTableActionPerformed

    private void btnAuthorToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorToTableActionPerformed
        String author = cBoxAuthor.getSelectedItem().toString();
        Boolean addToTable = true;
        if(authorCounter < 6) {
            for (int i = 0; i <= authorCounter; i++) {
                if (addManyTable.getValueAt(i, 0).toString().equalsIgnoreCase(author)) {
                    addToTable = false;
                }
            }
            if (addToTable) {
                addManyTable.setValueAt(author, authorCounter, 0);
                authorCounter++;
            } else {
                JOptionPane.showMessageDialog(null, "Kirjailija löytyy jo taulukosta", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kirjalla voi olla korkeintaan kuusi kirjailijaa", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAuthorToTableActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearBoxes();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        String name = txtBookName.getText();
        String origName = txtOriginalName.getText();
        String pubYear = txtPubYear.getText();
        String loaner = txtLoaner.getText();
        boolean onLoan = checkLoan.isSelected();
        ArrayList<Author> authors = new ArrayList();
        ArrayList<Category> categories = new ArrayList();

        for (int i = 0; i < authorCounter; i++) {
            Author a = new Author();
            String auth = addManyTable.getValueAt(i, 0).toString();
            String[] authName = auth.split(", ");
            String lName = authName[0];
            String fName = authName[1];
            a.getAuthor(fName, lName);
            a.getBooks();
            authors.add(a);
        }

        for (int i = 0; i < categoryCounter; i++) {
            Category c = new Category();
            String cat = addManyTable.getValueAt(i, 1).toString();
            c.getCategory(cat);
            categories.add(c);
        }

        if (checkPubYear(pubYear)) {
            if (!name.isEmpty()) {
                boolean bookExists = false;
                for (Author a : authors) {
                    for (Book bo : a.books) {
                        if (name.equalsIgnoreCase(bo.getName()) && Integer.parseInt(pubYear) == bo.getPubYear()) {
                            bookExists = true;
                        }
                    }
                }
                if (!bookExists) {
                    Book b = new Book(name, origName, Integer.parseInt(pubYear), onLoan, loaner);
                    for (Category c : categories) {
                        b.category.add(c);
                    }
                    for (Author a : authors) {
                        b.author.add(a);
                    }
                    b.addBook();
                    checkLoan.setSelected(false);
                    clearBoxes();
                } else {
                    JOptionPane.showMessageDialog(null, "Kirja löytyy jo tietokannasta", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoryActionPerformed
        //Storing whatever is in the txt field to variable
        String name = txtAddCategory.getText();

        if (!"".equalsIgnoreCase(name)) {
            if (!name.contains(" ")) {
                Category c = new Category(name);                            //if it isn't, create a new object
                if (!c.doesItExist()) {                                     //check whether the category already exists
                    c.addCategory();                                        //if it doesn't, add it to the database
                } else {                                                    //otherwise, display error dialog, tell user that the category already exists
                    JOptionPane.showMessageDialog(null, "Kategoria löytyy jo tietokannasta.", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Kategorian nimessä ei voi olla välilyöntiä", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tekstilaatikko oli tyhjä!", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE); //Inform user that the category text field was left blank
        }
        txtAddCategory.setText("");                //and finally, empty the text field
        comboCatRefresh();                      //Refresh 'categories' combobox contents
    }//GEN-LAST:event_btnAddCategoryActionPerformed

    private void btnAddAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAuthorActionPerformed
        String name = txtAddAuthorFirstName.getText();
        String lastName = txtAddAuthorLastName.getText();

        if (!"".equalsIgnoreCase(name) && !"".equalsIgnoreCase(lastName)) {          //check that neither field is empty
            Author a = new Author(name, lastName);                                  //If they aren't, create a new Author
            if (!a.doIExist()) {                                                     //check if the author already exists
                a.addAuthor();                                                      //If not, add him/her to the database
            } else {                                                                //Else inform the user that the author already exists
                JOptionPane.showMessageDialog(null, "Kirjailija löytyy jo tietokannasta.", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
            }
        } else if ("".equalsIgnoreCase(name)) {                                     //If the first check failed, inform user that name-field was emtpy
            JOptionPane.showMessageDialog(null, "Syötä myös etunimi!", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
        } else {                                                                    //If the second check failed, inform user that lastName-field was empty
            JOptionPane.showMessageDialog(null, "Syötä myös sukunimi!", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
        }
        txtAddAuthorFirstName.setText("");                                                   //Clear textfields
        txtAddAuthorLastName.setText("");                                                    //Clear textfields
        comboAuthorRefresh();                                                       //Refresh 'author' combobox contents
    }//GEN-LAST:event_btnAddAuthorActionPerformed

    private void cBoxEditAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxEditAuthorActionPerformed
        try {
            String author = cBoxEditAuthor.getSelectedItem().toString();
            if(author.length() < 1) {
              txtEditAuthorLastName.setText("");
              txtEditAuthorName.setText("");  
            } else {
                String[] authName = author.split(", ");
                String lName = authName[0];
                String fName = authName[1];
                txtEditAuthorLastName.setText(lName);
                txtEditAuthorName.setText(fName);
            }
        } catch(Exception e) {}
    }//GEN-LAST:event_cBoxEditAuthorActionPerformed

    private void cBoxEditCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxEditCategoryActionPerformed
        try {
            String category = cBoxEditCategory.getSelectedItem().toString();
            if(category.length() < 1) {
                txtEditCategory.setText("");
            } else {
                txtEditCategory.setText(category);
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_cBoxEditCategoryActionPerformed

    private void btnEditAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAuthorActionPerformed
        String author = cBoxEditAuthor.getSelectedItem().toString();
        String[] authName = author.split(", ");
        String oldName = authName[1];
        String oldLastName = authName[0];
        String name = txtEditAuthorName.getText();
        String lastName = txtEditAuthorLastName.getText();
        
        if (!"".equalsIgnoreCase(name) && !"".equalsIgnoreCase(lastName)) {
            Author a = new Author(oldName, oldLastName);
            a.getAuthor(oldName, oldLastName);
            a.setName(name);
            a.setLastName(lastName);
            if(!a.doIExist()) {
                a.updateAuthor();
                JOptionPane.showMessageDialog(null, "Kirjailija on päivitetty", "Ilmoitus", JOptionPane.PLAIN_MESSAGE);
                comboAuthorRefresh();
                txtEditAuthorName.setText("");
                txtEditAuthorLastName.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Kirjailija löytyy jo tietokannasta.", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
            }
        } else if ("".equalsIgnoreCase(name)) {
            JOptionPane.showMessageDialog(null, "Syötä myös etunimi!", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Syötä myös sukunimi!", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditAuthorActionPerformed

    private void btnEditCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCategoryActionPerformed
        String name = txtEditCategory.getText();
        String oldName = cBoxEditCategory.getSelectedItem().toString();

        if (!"".equalsIgnoreCase(name)) {
            if (!name.contains(" ")) {
                Category c = new Category(oldName);
                c.getCategory(oldName);
                c.setName(name);
                if (!c.doesItExist()) {
                    c.updateCategory();
                    JOptionPane.showMessageDialog(null, "Kategoria on päivitetty", "Ilmoitus", JOptionPane.PLAIN_MESSAGE);
                    comboCatRefresh();
                    txtAddCategory.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Kategoria löytyy jo tietokannasta.", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Kategorian nimessä ei voi olla välilyöntiä", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tekstilaatikko oli tyhjä!", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_btnEditCategoryActionPerformed

    private void btnClearEditBoxesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearEditBoxesActionPerformed
        clearEditBoxes();
    }//GEN-LAST:event_btnClearEditBoxesActionPerformed

    private void btnEditBookAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBookAddCategoryActionPerformed
        try {
            String category = cBoxEditBookCategory.getSelectedItem().toString();
            if(editBookTable.getRowCount() > 1) {
                for (int i = 0; i < 6; i++) {
                    if (category != null && category.length() != 0 ) {
                        if (editBookTable.getValueAt(i, 1).toString().equalsIgnoreCase(category)) {
                            JOptionPane.showMessageDialog(null, "Kategoria löytyy jo taulukosta", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
                            i = 6;
                        } else if (editBookTable.getValueAt(i, 1).toString().length() < 1) {
                            editBookTable.setValueAt(category, i, 1);
                            editBookCategoryCounter++;
                            i = 6;
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Valitse ensin selausvalikosta muokattava kirja", "Virhe", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valitse pudotusvalikosta lisättävä kategoria", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditBookAddCategoryActionPerformed

    private void btnEditBookDeleteAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBookDeleteAuthorActionPerformed
        try {
            int row = editBookTable.getSelectedRow();
            editBookTable.setValueAt("", row, 0);
            for(int i = row+1; i < 6; i++) {
                if(!editBookTable.getValueAt(i, 0).toString().equalsIgnoreCase("")) {
                    editBookTable.setValueAt(editBookTable.getValueAt(i, 0), i-1, 0);
                    editBookTable.setValueAt("", i, 0);
                    editBookAuthorCounter--;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valitse poistettava kirjailija klikkaamalla haluttua riviä taulukossa", "Virhe poistettaessa", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditBookDeleteAuthorActionPerformed

    private void btnEditBookDeleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBookDeleteCategoryActionPerformed
        try {
            int row = editBookTable.getSelectedRow();
            editBookTable.setValueAt("", row, 1);
            for(int i = row+1; i < 6; i++) {
                if(!editBookTable.getValueAt(i, 1).toString().equalsIgnoreCase("")) {
                    editBookTable.setValueAt(editBookTable.getValueAt(i, 1), i-1, 1);
                    editBookTable.setValueAt("", i, 1);
                    editBookCategoryCounter--;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valitse poistettava kategoria klikkaamalla haluttua riviä taulukossa", "Virhe poistettaessa", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditBookDeleteCategoryActionPerformed

    private void fillAddManyTable() {
        dtm.addRow(new Object[]{"", ""});
        dtm.addRow(new Object[]{"", ""});
        dtm.addRow(new Object[]{"", ""});
        dtm.addRow(new Object[]{"", ""});
        dtm.addRow(new Object[]{"", ""});
        dtm.addRow(new Object[]{"", ""});
        addManyTable.getColumnModel().getColumn(0).setMinWidth(205);
        addManyTable.getColumnModel().getColumn(0).setMaxWidth(205);
    }

    private void fillEditBookTable() {
        if (id != 0) {
            model.setRowCount(0);
            model.addRow(new Object[]{"", ""});
            model.addRow(new Object[]{"", ""});
            model.addRow(new Object[]{"", ""});
            model.addRow(new Object[]{"", ""});
            model.addRow(new Object[]{"", ""});
            model.addRow(new Object[]{"", ""});
            editBookTable.getColumnModel().getColumn(0).setMinWidth(205);
            editBookTable.getColumnModel().getColumn(0).setMaxWidth(205);

            Book b = new Book();
            b.getBook(id);
            txtEditBookName.setText(b.getName());
            txtEditPubYear.setText(b.getPubYear() + "");
            txtEditLoaner.setText(b.getLoaner());
            txtEditOrigName.setText(b.getOrigName());
            if (b.getOnLoan()) {
                checkEditLoan.setSelected(true);
            } else {
                checkEditLoan.setSelected(false);
            }

            b.getAuthors();
            b.getCategories();

            String authorName = "";
            int authorCount = 0;
            for (Author a : b.author) {
                authorName = a.getLastName() + ", " + a.getName();
                editBookTable.setValueAt(authorName, authorCount, 0);
                authorCount++;
            }
            String categoryName = "";
            int categoryCount = 0;
            for (Category c : b.category) {
                categoryName = c.getName();
                editBookTable.setValueAt(categoryName, categoryCount, 1);
                categoryCount++;
            }
        }
    }

    private void fillTable() {
        ArrayList<Book> books = Book.getBooks();
        mod.setRowCount(0);

        for (Book b : books) {
            String aName = "";
            b.getAuthors();
            int aCount = 1;
            for (Author a : b.author) {
                aName += a.getLastName() + ", " + a.getName();
                aName += aCount < b.author.size() ? " - " : "";
                aCount++;
            }

            String cat = "";
            b.getCategories();
            int bCount = 1;
            for (Category c : b.category) {
                cat += c.getName();
                cat += bCount < b.category.size() ? " - " : "";
                bCount++;
            }
            mod.addRow(new Object[]{b.getId(), aName, b.getName(), b.getPubYear(), cat, b.getOnLoan(), b.getLoaner(), b.getOrigName()});
        }
        mod.setRowCount(books.size() + 1);

        browseTable.getColumnModel().getColumn(0).setMaxWidth(40);
        browseTable.getColumnModel().getColumn(1).setMinWidth(220);
        browseTable.getColumnModel().getColumn(2).setMinWidth(200);
        browseTable.getColumnModel().getColumn(2).setMaxWidth(200);
        browseTable.getColumnModel().getColumn(3).setMinWidth(90);
        browseTable.getColumnModel().getColumn(3).setMaxWidth(90);
        browseTable.getColumnModel().getColumn(4).setMinWidth(160);

        centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        browseTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        browseTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        browseTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
    }

    private boolean checkPubYear(String pubYear) {

        boolean yearOk = false;
        if (!pubYear.isEmpty()) {
            if (pubYear.length() == 4) {
                try {
                    int pYear = Integer.parseInt(pubYear);
                    yearOk = true;
                } catch (NumberFormatException n) {
                    JOptionPane.showMessageDialog(null, "Syötä neljänumeroinen vuosiluku, esim '1994'", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
                    yearOk = false;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Syötä neljänumeroinen vuosiluku, esim '1994'", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Syötä julkaisuvuosi oli tyhjä", "Virhe lisätessä", JOptionPane.ERROR_MESSAGE);
        }
        return yearOk;
    }

    private void newFilter() {
        RowFilter<DefaultTableModel, Object> rf = null;
        try {
            rf = RowFilter.regexFilter("(?i)" + filterAuthor.getText());
        } catch (java.util.regex.PatternSyntaxException e) {
            return;
        }
        sorter.setRowFilter(rf);
    }

    //Clears all textfields in add-panel
    private void clearBoxes() {
        txtAddAuthorFirstName.setText("");
        txtAddAuthorLastName.setText("");
        txtAddCategory.setText("");
        txtBookName.setText("");
        txtLoaner.setText("");
        txtPubYear.setText("");
        txtOriginalName.setText("");
        checkLoan.setSelected(false);
        dtm.setRowCount(0);
        dtm.addRow(new Object[]{"", ""});
        dtm.addRow(new Object[]{"", ""});
        dtm.addRow(new Object[]{"", ""});
        dtm.addRow(new Object[]{"", ""});
        dtm.addRow(new Object[]{"", ""});
        dtm.addRow(new Object[]{"", ""});
        authorCounter = 0;
        categoryCounter = 0;
    }
    
    //Clears all textfields and the table in the edit-panel
    private void clearEditBoxes() {
        txtEditAuthorLastName.setText("");
        txtEditAuthorName.setText("");
        txtEditBookName.setText("");
        txtEditCategory.setText("");
        txtEditLoaner.setText("");
        txtEditOrigName.setText("");
        txtEditPubYear.setText("");
        cBoxEditAuthor.setSelectedIndex(-1);
        cBoxEditBookAuthor.setSelectedIndex(-1);
        cBoxEditBookCategory.setSelectedIndex(-1);
        cBoxEditCategory.setSelectedIndex(-1);
        model.setRowCount(0);
        checkEditLoan.setSelected(false);
        editBookAuthorCounter = 0;
        editBookCategoryCounter = 0;
    }

    /*
    * Get an arraylist of all authors
    * Remove all items from all author-related comboboxes used
    * For each author in the 'authors' -list...
    * ...add author name to every author-related combobox
    */
    private void comboAuthorRefresh() {
        ArrayList<Author> authors = Author.getAuthors();
        cBoxAuthor.removeAllItems();
        cBoxEditAuthor.removeAllItems();
        cBoxEditBookAuthor.removeAllItems();
        for (Author a : authors) {
            cBoxAuthor.addItem(a.getLastName() + ", " + a.getName());
            cBoxEditAuthor.addItem(a.getLastName() + ", " + a.getName());
            cBoxEditBookAuthor.addItem(a.getLastName() + ", " + a.getName());
        }
        cBoxAuthor.setSelectedIndex(-1);
        cBoxEditAuthor.setSelectedIndex(-1);
        cBoxEditBookAuthor.setSelectedIndex(-1);
    }

    /*
    * Fetch an arraylist of all categories in the database
    * Remove all items from all category-related comboboxes
    * For each category in 'categories'-list...
    * ...add category to all category-related comboboxes
    */
    private void comboCatRefresh() {
        ArrayList<Category> categories = Category.getCategories();
        cBoxCategory.removeAllItems();
        cBoxEditCategory.removeAllItems();
        cBoxEditBookCategory.removeAllItems();
        for (Category c : categories) {
            cBoxCategory.addItem(c.getName());
            cBoxEditCategory.addItem(c.getName());
            cBoxEditBookCategory.addItem(c.getName());
        }
        cBoxCategory.setSelectedIndex(-1);
        cBoxEditCategory.setSelectedIndex(-1);
        cBoxEditBookCategory.setSelectedIndex(-1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable addManyTable;
    private javax.swing.JTable browseTable;
    private javax.swing.JButton btnAddAuthor;
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnAuthorToTable;
    private javax.swing.JButton btnCatToTable;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearEditBoxes;
    private javax.swing.JButton btnEditAuthor;
    private javax.swing.JButton btnEditBookAddAuthor;
    private javax.swing.JButton btnEditBookAddCategory;
    private javax.swing.JButton btnEditBookDeleteAuthor;
    private javax.swing.JButton btnEditBookDeleteCategory;
    private javax.swing.JButton btnEditCategory;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JComboBox cBoxAuthor;
    private javax.swing.JComboBox cBoxCategory;
    private javax.swing.JComboBox cBoxEditAuthor;
    private javax.swing.JComboBox cBoxEditBookAuthor;
    private javax.swing.JComboBox cBoxEditBookCategory;
    private javax.swing.JComboBox cBoxEditCategory;
    private javax.swing.JCheckBox checkEditLoan;
    private javax.swing.JCheckBox checkLoan;
    private javax.swing.JTable editBookTable;
    private javax.swing.JTextField filterAuthor;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAddAuthor;
    private javax.swing.JLabel lblAddBook;
    private javax.swing.JLabel lblAddCategory;
    private javax.swing.JLabel lblAddCategoryHeader;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblEditAuthorFirstName;
    private javax.swing.JLabel lblEditAuthorHeader;
    private javax.swing.JLabel lblEditAuthorLastName;
    private javax.swing.JLabel lblEditBookHeader;
    private javax.swing.JLabel lblEditBookName;
    private javax.swing.JLabel lblEditBookOrigName;
    private javax.swing.JLabel lblEditBookPubYear;
    private javax.swing.JLabel lblEditCategoryHeader;
    private javax.swing.JLabel lblEditCategoryName;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblOrigName;
    private javax.swing.JLabel lblPubYear;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStar;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelBrowse;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    private javax.swing.JTextField txtAddAuthorFirstName;
    private javax.swing.JTextField txtAddAuthorLastName;
    private javax.swing.JTextField txtAddCategory;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtEditAuthorLastName;
    private javax.swing.JTextField txtEditAuthorName;
    private javax.swing.JTextField txtEditBookName;
    private javax.swing.JTextField txtEditCategory;
    private javax.swing.JTextField txtEditLoaner;
    private javax.swing.JTextField txtEditOrigName;
    private javax.swing.JTextField txtEditPubYear;
    private javax.swing.JTextField txtLoaner;
    private javax.swing.JTextField txtOriginalName;
    private javax.swing.JTextField txtPubYear;
    // End of variables declaration//GEN-END:variables
}
